server:
  port: 8080 # Cổng mặc định

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:default_db}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # update, validate, hoặc none cho production
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Cấu hình để actuator/health được public
management:
  endpoints:
    web:
      exposure:
        include: "health,info"